[project]
name = "qdsp-sim"
version = "0.1.0"
description = "Educational VLIW DSP Simulator"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.8"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
